# Coding Assingment 4

## Problem 1

In [3]:
# Import data
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

# Load the dataset
wine = load_wine()
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = wine.target

X.shape


(178, 13)

In [4]:
# train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=598, stratify=y
)

### 1a) Fit LDA, QDA, and Multinomial (Logistic) Regression 

In [13]:
# Train LDA and QDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

lda_train_pred = lda.predict(X_train)
lda_test_pred = lda.predict(X_test)

qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train, y_train)

qda_train_pred = qda.predict(X_train)
qda_test_pred = qda.predict(X_test)

In [14]:
# Train Multinomial Logistic Regression 
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

log_reg = make_pipeline(
    StandardScaler(),
    LogisticRegression(solver='lbfgs', max_iter=2000, random_state=598)
)
log_reg.fit(X_train, y_train)

log_train_pred = log_reg.predict(X_train)
log_test_pred = log_reg.predict(X_test)



### 1b) Accuracy on training and testing and confusion matrices

In [16]:
# Create a table for showing the accuracy  
results = pd.DataFrame({
    "Model": ["LDA", "QDA", "Logistic Regression"],
    "Training Accuracy": [
        accuracy_score(y_train, lda_train_pred),
        accuracy_score(y_train, qda_train_pred),
        accuracy_score(y_train, log_train_pred)
    ],
    "Testing Accuracy": [
        accuracy_score(y_test, lda_test_pred),
        accuracy_score(y_test, qda_test_pred),
        accuracy_score(y_test, log_test_pred)
    ]
})

results

,Model,Training Accuracy,Testing Accuracy
0,LDA,1.0,1.0
1,QDA,1.0,1.0
2,Logistic Regression,1.0,1.0


In [17]:
# Create a confusion matrices
print("Confusion Matrices:\n")
print("LDA:\n", confusion_matrix(y_test, lda_test_pred))
print("\nQDA:\n", confusion_matrix(y_test, qda_test_pred))
print("\nLogistic Regression:\n", confusion_matrix(y_test, log_test_pred))


Confusion Matrices:

LDA:
 [[18  0  0]
 [ 0 21  0]
 [ 0  0 15]]

QDA:
 [[18  0  0]
 [ 0 21  0]
 [ 0  0 15]]

Logistic Regression:
 [[18  0  0]
 [ 0 21  0]
 [ 0  0 15]]


### 1c) Results

All three classification methods achieved perfect accuracy on both the training and testing datasets, correctly classifying all wine samples. The identical confusion matrices indicate that no misclassifications occurred. This implies that the chemical characteristics measured provide strong linear separability between the grape cultivars. 

Since both LDA and Logistic Regression, which rely on linear decision boundaries, performed as well as QDA, it appears that the additional flexibility of QDA is unnecessary for this dataset. Thus, all models performed equally well, but LDA or Logistic Regression would be preferred for their simplicity and interpretability.

## Problem 2


In [22]:
# Load the data
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
pen_based_recognition_of_handwritten_digits = fetch_ucirepo(id=81) 
  
# data (as pandas dataframes) 
X = pen_based_recognition_of_handwritten_digits.data.features 
y = pen_based_recognition_of_handwritten_digits.data.targets 

In [23]:
# Split testing and training 
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=598, stratify=y
)

### 2a) SVM classifier with a Gaussian kernel on training set 

In [26]:
# need to make sure y_train and y_test are 1d arrays, not 2d
y_train = y_train.values.ravel()
y_test = y_test.values.ravel()

In [27]:
from sklearn.svm import SVC

svm_rbf = make_pipeline(
    StandardScaler(),              
    SVC(kernel='rbf', gamma='scale', C=1.0, random_state=598)
)
svm_rbf.fit(X_train, y_train)

,steps,"[('standardscaler', ...), ('svc', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'


### 2b) Decision tree classifier on training set

In [28]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=598)
dt_model.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,598
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


### 2c) Fitting Gradient Boosting and AdaBoost on training set
I chose those two simply out of personal preference. The instructions stated to just fit two. 

In [32]:
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier

gb_model = GradientBoostingClassifier(random_state=598)
gb_model.fit(X_train, y_train)

,loss,'log_loss'
,learning_rate,0.1
,n_estimators,100
,subsample,1.0
,criterion,'friedman_mse'
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_depth,3
,min_impurity_decrease,0.0
,init,None


In [33]:
ab_model = AdaBoostClassifier(random_state=598)
ab_model.fit(X_train, y_train)

,estimator,None
,n_estimators,50
,learning_rate,1.0
,algorithm,'deprecated'
,random_state,598


### 2d) Report the accuracy for all classifiers 

In [35]:
# SVM Results
y_train_pred_svm = svm_rbf.predict(X_train)
y_test_pred_svm = svm_rbf.predict(X_test)

train_acc = accuracy_score(y_train, y_train_pred_svm)
test_acc = accuracy_score(y_test, y_test_pred_svm)

print(f"SVM - Training Accuracy: {train_acc:.3f}")
print(f"SVM - Testing Accuracy: {test_acc:.3f}")

SVM - Training Accuracy: 0.996
SVM - Testing Accuracy: 0.995


In [36]:
# Decision Tree Results
y_train_pred_dt = dt_model.predict(X_train)
y_test_pred_dt = dt_model.predict(X_test)

train_acc = accuracy_score(y_train, y_train_pred_dt)
test_acc = accuracy_score(y_test, y_test_pred_dt)

print(f"Decision Tree - Training Accuracy: {train_acc:.3f}")
print(f"Decision Tree - Testing Accuracy: {test_acc:.3f}")

Decision Tree - Training Accuracy: 1.000
Decision Tree - Testing Accuracy: 0.957


In [37]:
# AdaBoost Results
y_train_pred_ab = ab_model.predict(X_train)
y_test_pred_ab = ab_model.predict(X_test)

train_acc = accuracy_score(y_train, y_train_pred_ab)
test_acc = accuracy_score(y_test, y_test_pred_ab)

print(f"AdaBoost - Training Accuracy: {train_acc:.3f}")
print(f"AdaBoost - Testing Accuracy: {test_acc:.3f}")

AdaBoost - Training Accuracy: 0.602
AdaBoost - Testing Accuracy: 0.609


In [38]:
# Gradient Boosting Results
y_train_pred_gb = gb_model.predict(X_train)
y_test_pred_gb = gb_model.predict(X_test)

train_acc = accuracy_score(y_train, y_train_pred_gb)
test_acc = accuracy_score(y_test, y_test_pred_gb)

print(f"Gradient Boosting - Training Accuracy: {train_acc:.3f}")
print(f"Gradient Boosting - Testing Accuracy: {test_acc:.3f}")

Gradient Boosting - Training Accuracy: 1.000
Gradient Boosting - Testing Accuracy: 0.990


### 2e) Confusion matrices for test predictions

In [39]:
print("Confusion Matrix for SVM")
confusion_matrix(y_test, y_test_pred_svm)


Confusion Matrix for SVM


array([[343,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 341,   0,   0,   0,   0,   0,   2,   0,   0],
       [  0,   1, 341,   0,   0,   0,   0,   1,   0,   0],
       [  0,   0,   2, 312,   0,   1,   0,   0,   0,   1],
       [  0,   0,   0,   0, 343,   0,   0,   0,   0,   0],
       [  0,   0,   0,   2,   0, 313,   0,   0,   0,   1],
       [  0,   0,   0,   0,   0,   0, 317,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 343,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   1, 316,   0],
       [  0,   0,   0,   0,   0,   1,   0,   1,   1, 314]])

In [40]:
print("Confusion Matrix for Decision Tree")
confusion_matrix(y_test, y_test_pred_dt)

Confusion Matrix for Decision Tree


array([[338,   0,   0,   0,   2,   0,   0,   0,   3,   0],
       [  0, 317,  15,   4,   2,   0,   0,   4,   0,   1],
       [  0,  17, 324,   1,   0,   0,   0,   0,   1,   0],
       [  0,   1,   4, 299,   1,   4,   0,   1,   1,   5],
       [  1,   0,   0,   0, 338,   1,   0,   1,   0,   2],
       [  1,   1,   1,   1,   0, 306,   2,   0,   1,   3],
       [  3,   2,   1,   0,   2,   1, 306,   0,   1,   1],
       [  0,   8,   0,   1,   0,   0,   1, 327,   5,   1],
       [  5,   0,   2,   1,   0,   1,   0,   5, 303,   0],
       [  3,   1,   0,   3,   4,   7,   0,   0,   2, 297]])

In [41]:
print("Confusion Matrix for AdaBoost")
confusion_matrix(y_test, y_test_pred_ab)

Confusion Matrix for AdaBoost


array([[229,   0,   0,   1,   3,  11,   0,   4,  92,   3],
       [  0,  69,  82,  32,   2,   3,   0,   0,   0, 155],
       [  0,  55, 274,   1,   0,  11,   0,   1,   0,   1],
       [  0,   9,   1, 306,   0,   0,   0,   0,   0,   0],
       [  0,   1,   0,   0, 300,  12,   8,   0,   0,  22],
       [ 65,   2,   0,  82,   0,  81,   0,   0,  83,   3],
       [  0,   1,   1,   2,  23,  64, 218,   0,   8,   0],
       [  2,   8,   1,   4,   0,  10,   1, 255,  23,  39],
       [ 82,   0,   0,   8,   0,  22,   0,   1, 204,   0],
       [  0,   1,   0, 171,   2,  47,   0,  16,   6,  74]])

In [42]:
print("Confusion Matrix for Gradient Boosting")
confusion_matrix(y_test, y_test_pred_gb)

Confusion Matrix for Gradient Boosting


array([[339,   0,   0,   0,   2,   0,   0,   0,   1,   1],
       [  0, 339,   3,   0,   0,   0,   0,   1,   0,   0],
       [  0,   3, 339,   0,   0,   0,   0,   1,   0,   0],
       [  0,   1,   1, 312,   0,   0,   0,   1,   0,   1],
       [  0,   0,   0,   0, 343,   0,   0,   0,   0,   0],
       [  0,   0,   0,   1,   0, 314,   0,   0,   0,   1],
       [  1,   0,   0,   0,   0,   0, 315,   0,   1,   0],
       [  0,   3,   0,   0,   0,   0,   0, 338,   2,   0],
       [  1,   0,   0,   0,   0,   0,   2,   0, 313,   1],
       [  0,   1,   0,   0,   0,   1,   0,   0,   1, 314]])

### 2f) Comment on Results

The best performing model was the SVM. It had a high accuracy with minimal overfitting. The Decision Tree and Gradient Boosting show slight overfitting because the training accuracy was 1.0 and testing was slightly lower than 1.0 for both models. 

There was confusion between digits that look similar to each other: 
- 1 vs. 7, 2 vs. 1, 3 vs. 9, 6 vs. 8, and 0 vs. 8
